config/routes.rb
Rails.application.routes.draw do
  get 'author/session'

  resources :articles do
    resources :comments
  end

  root "articles#index"

  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
  has_attached_file :image, styles: { medium: "400x400>", thumb: "100x100>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
	validates_presence_of :title, :body
  validates_uniqueness_of :title, {message: "Already taken!"}
  self.per_page = 7
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "Should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
	validates_presence_of :author_name, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :js, :json
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
before_filter :require_login, except: [:index, :show]

	def index
		@articles = Article.order('created_at DESC').page(params[:page])
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article_id
		@comments = @article.comments.order('created_at DESC')
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if @article.save
			flash.notice = "You've just posted #{@article.title}"
			redirect_to article_path(@article)
		else
			flash.notice = "Your post wasn't saved properly!"
			render("new")
		end
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update_attributes(article_params)
		flash.notice = "#{@article.title} has successfully been updated!"
		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash.notice = "#{@article.title} has been forever deleted!"
		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :body, :image)
	end
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	def new
	end

	def create
		if login(params[:email], params[:password])
			redirect_to root_path
			flash.notice = "Welcome back Johnny ;)"
		else
			flash.now.alert = "Login failed!"
			render "new"
		end
	end

	def destroy 
		logout
		redirect_to :authors, notice: 'Logged out!'
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def create
    @author = Author.new(author_params)
    @author.save ? redirect_to(root_path, notice: 'Author was successfully created.') : render('new')
  end

  def update
    @author.update(author_params) ? redirect_to(root_path, notice: 'Author was successfully updated.') : render(:edit)
  end

  def destroy
    @author.destroy
    redirect_to(authors_url, notice: 'Author was successfully destroyed.')
  end

  private

    def set_author
      @author = Author.find(params[:id])
    end

    def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end

    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :require_login, except: [:create]
	
	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		@comment.save ? redirect_to(article_path(@comment.article), notice: 'Thanks for the comment!') : redirect_to(article_path(@comment.article), notice: 'You\'re comment wasn\'t properly saved!')
	end

	def destroy
		@article = Article.find(params[:article_id])
		@comment = @article.comments.find(params[:id])
		@comment.destroy
		redirect_to article_path(@comment.article)
	end

	private

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end

	def refresh_with_message(message)
		redirect_to article_path(@comment.article), notice: message
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_article.html.erb
<div class="article">
  <h3 class='article-title'><%= link_to article.title, article_path(article)%></h3>
  <p class='article-date'><%= article.created_at.strftime("%B %d, %Y") %></p>
  <p class="article-body"><%= link_to(truncate(article.body.html_safe, length: 225, omission: '...', separator: /\.\s/, escape: false), article_path(article))%></p>
</div>

app/views/articles/_comment.html.erb
<div class="comment">
	<h4 class="author-name"><%= comment.author_name %></h4>
	
	<% if logged_in? %>
	 <%= link_to 'Delete', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "confirm-button" %>
	<% else %>
    <p class="comment-time">posted <%= time_ago_in_words(comment.created_at) %> ago</p>
	<% end %>
  
	<p class="comment-body"><%= comment.body.html_safe %></p>
</div>

app/views/articles/_form.html.erb
<%= tinymce_assets %>

<div class="article-form">
	<%= form_for(@article, html: {multipart: true}) do |f| %>
		<% if @article.errors.any? %>
			<ul>
				<% @article.errors.full_messages.each do |error| %>
				<li><%= error %></li>
				<% end %>
			</ul>
		<% end %>
			<%= f.label :title, 'Post Title', class: "article-label"%><br>
			<%= f.text_field :title, class: 'article-title-field' %><br><br><br>
			<%= f.text_area :body, class: "article-area tinymce" %>
				<br><br><br>
			<%= f.submit 'submit here', class: "confirm-button" %>
		</p>
	<% end %>
</div>

<%= tinymce %>

app/views/articles/edit.html.erb
<h1>Lets make some changes...</h1>

<%= render partial: 'form' %>

<%= link_to "nevermind", article_path, class: "confirm-button" %>

app/views/articles/index.html.erb
<header>
	<div class="social-icons">
		<a href="https://github.com/johnnyji/" target="_blank" ><i class="fa fa-github"></i></a>
		<a href="http://www.linkedin.com/in/johnnyji" target="_blank" ><i class="fa fa-linkedin"></i></a>
		<a href="http://www.instagram.com/johnnyisji" target="_blank" ><i class="fa fa-instagram"></i></a>
		<a href="https://twitter.com/johnnyisji" target="_blank" ><i class="fa fa-twitter"></i></a>
	</div>
	<p class='intro'>Hello, I'm <b><a href="http://johnnyji.com/" target="_blank">Johnny Ji</a></b> and the following is a collection of my experiences as a web developer and a human being in training.</p>
</header>

<br>

<% if logged_in? %>
	<%= link_to "Create a New Article", new_article_path, class: "confirm-button" %>
<% end %>

<div class="articles-container">
	<%= render @articles %>
</div>

<%= will_paginate @articles, previous_label: "Prev", next_label: "Next" %>

app/views/articles/index.js.erb
$('.articles-container').append('<%= j render(@articles) %>');
<% if @articles.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@articles) %>');
<% else %>
  $('.pagination').remove()
<% end %>

<% sleep 1 %>

app/views/articles/new.html.erb
<a href="<%= root_path %>" class='home-button'>
  <i class="fa fa-chevron-left"></i>
</a>

<h1 class='new-article-title'>Make a new post!</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<!-- GO BACK TO ROOT BUTTON -->
<a href="<%= root_path %>" class='home-button'>
	<i class="fa fa-chevron-left"></i>
</a>

<!-- THE POST BODY -->
<div class="current-article">
	<h1 class='title'><b><%= @article.title.html_safe %></b></h1>

	<% if logged_in? %>
		<div class="edit-delete">
			<%= link_to "edit post", edit_article_path(@article) , class: "confirm-button" %> &nbsp;
			<%= link_to "delete post", article_path(@article) , method: :delete, data: {confirm: 'Are you sure?'}, class: "confirm-button" %>
		</div>
	<% end %>

	<p class="current-article-date"><%= @article.created_at.strftime('%B %d, %Y') %></p>
	<p class="current-article-body"><%= @article.body.html_safe %></p>

	<p class="current-article-image">
		<% if @article.image.exists? %>
      <%= image_tag @article.image.url(:medium).html_safe %><br/>
  	<% end %>
	</p>
</div>


<!-- COMMENT SECTION -->
<div class='comment-section'>
	<% if @comments.size < 1 %>
		<h3>No comments yet</h3>
	<% elsif @comments.size == 1 %>
		<h3><%= @comments.size %>&nbsp;Comment</h3>
	<% else %>
		<h3><%= @comments.size %>&nbsp;Comments</h3>
	<% end %>
	<%= render partial: "comment", collection: @comments %>
</div>

<%= render partial: "comments/form" %>

app/views/author/session.html.erb
<h1>Author#session</h1>
<p>Find me in app/views/author/session.html.erb</p>

app/views/author_sessions/new.html.erb
<h1>login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email, "email", class: "field_name" %><br>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <br>
  <div class="field">
    <%= label_tag :password, "password", class: "field_name" %><br>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <br><br>
  <div class="actions">
    <%= submit_tag "enter", class: "confirm-button" %>
  </div>
<% end %>

<%= link_to 'go back', articles_path, class: "confirm-button" %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'new author', new_author_path %><br>
<%= link_to 'go back', articles_path %>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<div class="comment-form">
	<%= form_for [@article, @comment] do |f| %>
		<%= f.text_field :author_name, placeholder: 'Your name', class: "comment-area-name", autofocus: true %><br>
		<%= f.text_area :body, placeholder: 'Your thoughts...', class: "comment-area" %><br><br>
		<%= f.submit 'submit here', class: "confirm-button" %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Johnny Ji</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= stylesheet_link_tag 'application', 'http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css', media: 'all' %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600,300', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'favicon.ico' %>
</head>

<div class="app-wrapper">
<body>
  <%= tinymce_assets %>
  <p class="flash"><%= flash.notice %></p>

  <!-- YIELD CONTENT -->
  <%= yield %>

  <footer>
    &copy; <%= I18n.t("date.abbr_month_names")[Date.today.month] %> <%= Time.now.year %> Johnny Ji | Check out my portfolio 
    <a href="http://www.johnnyji.com/" target="_blank">here!</a>
    <% if logged_in? %> 
      <%= link_to "Logout", logout_path %> 
    <% end %>
  </footer>
  <%= tinymce %>
</body>
</div>
</html>